---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04
  - name: centos-7.1
  - name: centos-6.7
  - name: windows-2012r2
    driver:
      box: windows-2012r2
    transport:
      name: winrm
      password: vagrant
      username: vagrant

suites:
  - name: default
    data_bags_path: test/integration/data_bags
    run_list:
      - recipe[data-bag-faker]
      - recipe[sumologic-collector::default]
    attributes:
      SUMO_ACCESS_ID: <%= ENV['SUMO_ACCESS_ID'] %>
      SUMO_ACCESS_KEY: <%= ENV['SUMO_ACCESS_KEY'] %>
    excludes:
      - windows-2012r2
  - name: windows
    data_bags_path: test/integration/data_bags
    run_list:
      - recipe[data-bag-faker]
      - recipe[sumologic-collector::windows]
    attributes:
      SUMO_ACCESS_ID: <%= ENV['SUMO_ACCESS_ID'] %>
      SUMO_ACCESS_KEY: <%= ENV['SUMO_ACCESS_KEY'] %>
    excludes:
      - ubuntu-14.04
      - centos-7.1
      - centos-6.7
      